
from enum import Enum


DELIMITER = "\a\b"


class Side(Enum):
    SERVER = 1
    CLIENT = 0


class Orientation(Enum):
    NORTH = 1
    SOUTH = -1
    EAST = 2
    WEST = -2



class ServerMessages(Enum):
    KEY_REQUEST = "107 KEY REQUEST" + DELIMITER
    CONFIRMATION = "" + DELIMITER
    MOVE = "102 MOVE" + DELIMITER
    TURN_LEFT = "103 TURN LEFT" + DELIMITER
    TURN_RIGHT = "104 TURN RIGHT" + DELIMITER
    PICK_UP = "105 GET MESSAGE" + DELIMITER
    LOGOUT = "106 LOGOUT" + DELIMITER
    OK = "200 OK" + DELIMITER
    LOGIN_FAILED = "300 LOGIN FAILED" + DELIMITER
    SYNTAX_ERROR = "301 SYNTAX ERROR" + DELIMITER
    LOGIC_ERROR = "302 LOGIC ERROR" + DELIMITER
    KEY_OUT_OF_RANGE_ERROR = "303 KEY OUT OF RANGE" + DELIMITER
